<?php
/**
 * @file
 *   Adminhtml configuration template for kreXX
 *   kreXX: Krumo eXXtended
 *
 *   This is a debugging tool, which displays structured information
 *   about any PHP object. It is a nice replacement for print_r() or var_dump()
 *   which are used by a lot of PHP developers.
 *
 *   kreXX is a fork of Krumo, which was originally written by:
 *   Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author brainworXX GmbH <info@brainworxx.de>
 *
 * @license http://opensource.org/licenses/LGPL-2.1
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2015 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/* @var Brainworxx_Includekrexx_Block_Adminhtml_Krexx $this */
?>

<h1>Administer kreXX FE Editing</h1>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="editconfig" >
  <table border="0" class="krexx-config">
    <tr>
      <th colspan="3"><b>Here you can edit the frontend configuration form.</b></th>
    </tr>
    <tr>
      <td>full edit</td>
      <td colspan="2"> = The value can be edited in the frontend.</td>
    </tr>
    <tr>
      <td>display</td>
      <td colspan="2"> = The value will only be displayed.</td>
    </tr>
    <tr>
      <td>do not display</td>
      <td colspan="2"> = kreXX will not display the value.</td>
    </tr>
    <tr><td colspan="3">&nbsp;</td></tr>
    <tr>
      <th colspan="3"><b>Render</b></th>
    </tr>
    <tr>
      <td><label for="skin">Skin</label></td>
      <td>
        <select name="render[skin]" id="skin">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['render']['skin']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.skin" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['skin']; ?>/>
        <label for="factory.skin">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="memoryLeft">Minimum amout of memory [MB]</label></td>
      <td>
        <select name="render[memoryLeft]" id="memoryLeft">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['render']['memoryLeft']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.memoryLeft" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['memoryLeft']; ?>/>
        <label for="factory.memoryLeft">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="maxRuntime">Maximum Runtime [Seconds]</label></td>
      <td>
        <select name="render[maxRuntime]" id="maxRuntime">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['render']['maxRuntime']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.maxRuntime" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['maxRuntime']; ?>/>
        <label for="factory.maxRuntime">Use factory settings</label>
      </td>
    </tr>
    <tr><td colspan="3">&nbsp;</td></tr>
    <tr>
      <th colspan="3"><b>Logging</b></th>
    </tr>
    <tr>
      <td><label for="folder">Folder:</label></td>
      <td>
        <select name="logging[folder]" id="folder">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['logging']['folder']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.folder" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['folder']; ?>/>
        <label for="factory.folder">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="maxfiles">Maximum files in the logfolder:</label></td>
      <td>
        <select name="logging[maxfiles]" id="maxfiles">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['logging']['maxfiles']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.maxfiles" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['maxfiles']; ?>/>
        <label for="factory.maxfiles">Use factory settings</label>
      </td>
    </tr>
    <tr><td colspan="3">&nbsp;</td></tr>
    <tr>
      <th colspan="3"><b>Output</b></th>
    </tr>
    <tr>
      <td><label for="destination">Destination:</label></td>
      <td>
        <select name="output[destination]" id="destination">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['output']['destination']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.destination" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['destination']; ?>/>
        <label for="factory.destination">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="maxCall">Maximum amount of calls:</label></td>
      <td>
        <select name="output[maxCall]" id="maxCall">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['output']['maxCall']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.maxCall" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['maxCall']; ?>/>
        <label for="factory.maxCall">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="disabled">Disable output:</label></td>
      <td>
        <select name="output[disabled]" id="disabled">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['output']['disabled']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.disabled" class="checkbox" type="checkbox" value="1" name="factory"  <?php echo $factory['disabled']; ?>/>
        <label for="factory.disabled">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="detectAjax">Try to detect AJAX requests:</label></td>
      <td>
        <select name="output[detectAjax]" id="detectAjax">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['output']['detectAjax']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.detectAjax" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['detectAjax']; ?>/>
        <label for="factory.detectAjax">Use factory settings</label>
      </td>
    </tr>
    <tr><td colspan="3">&nbsp;</td></tr>
    <tr>
      <th colspan="3"><b>Deep</b></th>
    </tr>
    <tr>
      <td><label for="analyseProtected">Analyse protected properties:</label></td>
      <td>
        <select name="deep[analyseProtected]" id="analyseProtected">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['deep']['analyseProtected']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.analyseProtected" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseProtected']; ?>/>
        <label for="factory.analyseProtected">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="analysePrivate">Analyse private properties:</label></td>
      <td>
        <select name="deep[analysePrivate]" id="analysePrivate">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['deep']['analysePrivate']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.analysePrivate" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analysePrivate']; ?>/>
        <label for="factory.analysePrivate">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="analyseTraversable">Analyse traversable data:</label></td>
      <td>
        <select name="deep[analyseTraversable]" id="analyseTraversable">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['deep']['analyseTraversable']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.analyseTraversable" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseTraversable']; ?>/>
        <label for="factory.analyseTraversable">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="debugMethods">List of debug methods to poll for data:</label></td>
      <td>
        <select name="deep[debugMethods]" id="debugMethods">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['deep']['debugMethods']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.debugMethods" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['debugMethods']; ?>/>
        <label for="factory.debugMethods">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="level">Maximum nesting level:</label></td>
      <td>
        <select name="deep[level]" id="level">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['deep']['level']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.level" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['level']; ?>/>
        <label for="factory.level">Use factory settings</label>
      </td>
    </tr>
    <tr><td colspan="3">&nbsp;</td></tr>
    <tr>
      <th colspan="3"><b>Methods</b></th>
    </tr>
    <tr>
      <td><label for="analyseMethodsAtall">Analyse public methods:</label></td>
      <td>
        <select name="methods[analyseMethodsAtall]" id="analyseMethodsAtall">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['methods']['analyseMethodsAtall']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.analyseMethodsAtall" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseMethodsAtall']; ?>/>
        <label for="factory.analyseMethodsAtall">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="analyseProtectedMethods">Analyse protected methods:</label></td>
      <td>
        <select name="methods[analyseProtectedMethods]" id="analyseProtectedMethods">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['methods']['analyseProtectedMethods']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.analyseProtectedMethods" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseProtectedMethods']; ?>/>
        <label for="factory.analyseProtectedMethods">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="analysePrivateMethods">Analyse private methods:</label></td>
      <td>
        <select name="methods[analysePrivateMethods]" id="analysePrivateMethods">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['methods']['analysePrivateMethods']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.analysePrivateMethods" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analysePrivateMethods']; ?>/>
        <label for="factory.analysePrivateMethods">Use factory settings</label>
      </td>
    </tr>
    <tr><td colspan="3">&nbsp;</td></tr>
    <tr>
      <th colspan="3"><b>Error Handling and Backtrace</b></th>
    </tr>
    <tr>
      <td><label for="registerAutomatically">Register fatal error handler automatically:</label></td>
      <td>
        <select name="errorHandling[registerAutomatically]" id="registerAutomatically">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['errorHandling']['registerAutomatically']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.registerAutomatically" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['registerAutomatically']; ?>/>
        <label for="factory.registerAutomatically">Use factory settings</label>
      </td>
    </tr>
    <tr>
      <td><label for="backtraceAnalysis">Backtrace analysis settings:</label></td>
      <td>
        <select name="errorHandling[backtraceAnalysis]" id="backtraceAnalysis">
          <?php foreach($data['settings'] as $key => $value) {
                if ($key == $settings['errorHandling']['backtraceAnalysis']) {
                  $selected = 'selected="selected"';
                }
                else {
                  $selected = '';
                }
          ?>
          <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
          <?php }?>
        </select>
      </td>
      <td>
        <input id="factory.backtraceAnalysis" class="checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['backtraceAnalysis']; ?>/>
        <label for="factory.backtraceAnalysis">Use factory settings</label>
      </td>
    </tr>
  </table>
  <br/>
  <?php echo $this->getBlockHtml('formkey')?>
  <input type="submit" value="Save configuration">
</form>

<style type="text/css">
input:disabled{
  color: #dddddd;
  border: #dddddd 1px solid;
  background-color: #fff;
}
select:disabled {
  color: #dddddd;
}
select {
  min-width: 137px;
}
.link-store-scope {
  cursor: help;
}
</style>

<script type="text/javascript">
document.observe("dom:loaded", function() {
  var checkboxes = document.getElementsByName('factory');
  var id, element;

  for(var i=0, n=checkboxes.length; i<n;i++) {
    toggle(checkboxes[i]);
    // var checkbox[i] = checkboxes[i]
    checkboxes[i].addEventListener('click', function() {toggle(this);}, true);
  }

  var savebutton = document.getElementById('editconfig_save');
  if (typeof savebutton === 'object' && savebutton != 'undefined' && savebutton != null) {
    savebutton.addEventListener('click', function() {
      var form = document.getElementById('editconfig');
      if (typeof form === 'object' && form != 'undefined' && form != null) {
        form.submit();
      }
    }, true);
  }

});

toggle = function(checkbox) {
  var id = checkbox.id.split('.');
  if(id[1] != 'undefined') {
    var element = document.getElementById(id[1]);
  }

  if (typeof element === 'object' && element != 'undefined' && element != null) {


    if (checkbox.checked) {
      element.disabled = true;
    }
    else {
      element.disabled = false;
    }
  }
};
</script>